# Generated by Django 4.0.5 on 2022-07-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DecimalField(decimal_places=13, max_digits=23)),
                ('par1', models.FloatField()),
                ('par2', models.FloatField()),
                ('par3', models.FloatField()),
                ('par4', models.FloatField()),
                ('par5', models.FloatField()),
            ],
        ),
    ]
