# Generated by Django 4.0.5 on 2022-07-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anapp', '0004_alter_data_par1_alter_data_par2_alter_data_par3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='par1',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='data',
            name='par2',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='data',
            name='par3',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='data',
            name='par4',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='data',
            name='par5',
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10000),
        ),
    ]
